export const CREATE_USER = "CREATE_USER";
export const AUTH_USER = "AUTH_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const MAKE_POST = "MAKE_POST";
